In [56]:
import pandas as pd
import numpy as np 
import pandas_profiling as pdp
import matplotlib as plt

In [38]:
test = pd.read_csv('../assets/test.csv', index_col='Id')

In [39]:
test.head()

,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy
Id,,,,,,,,,,
1,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
2,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
3,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
4,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX SALINARIUS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
5,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX TERRITANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9

In [40]:
pdp.ProfileReport(test)

In [41]:
pdp.describe(test)

{'freq': {'Address': ORD Terminal 5, O'Hare International Airport, Chicago, IL 60666, USA    1468
  4100 North Oak Park Avenue, Chicago, IL 60634, USA                       857
  7000 North Moselle Avenue, Chicago, IL 60646, USA                        822
  3600 North Pittsburgh Avenue, Chicago, IL 60634, USA                     814
  5800 North Pulaski Road, Chicago, IL 60646, USA                          803
  7000 West Armitage Avenue, Chicago, IL 60707, USA                        797
  2200 North Cannon Drive, Chicago, IL 60614, USA                          792
  Ohare Court, Bensenville, IL 60106, USA                                  784
  5800 North Western Avenue, Chicago, IL 60659, USA                        783
  6100 North Lemont Avenue, Chicago, IL 60646, USA                         781
  5800 North Ridge Avenue, Chicago, IL 60660, USA                          781
  4600 Milwaukee Avenue, Chicago, IL 60630, USA                            780
  1000 East 67th Street, Chicago, IL 60637, USA                            776
  South Doty Avenue, Chicago, IL, USA                                      776
  4500 North Campbell Avenue, Chicago, IL 60625, USA                       776
  7200 North Oketo Avenue, Chicago, IL 60631, USA                          775
  5100 North Mont Clare Avenue, Chicago, IL 60656, USA                     774
  4200 West 127th Street, Alsip, IL 60803, USA                             774
  2400 East 105th Street, Chicago, IL 60617, USA                           774
  3700 South Pulaski Road, Chicago, IL 60623, USA                          774
  3700 118th Street, Chicago, IL 60617, USA                                773
  3500 West 116th Street, Chicago, IL 60655, USA                           773
  5200 South Kolmar Avenue, Chicago, IL 60632, USA                         772
  South Cottage Grove Avenue, Chicago, IL, USA                             772
  1000 North Central Park Avenue, Chicago, IL 60651, USA                   771
  8900 South Carpenter Street, Chicago, IL 60620, USA                      770
  4000 East 130th Street, Chicago, IL 60633, USA                           769
  6100 West Fullerton Avenue, Chicago, IL 60639, USA                       769
  2800 North Francisco Avenue, Chicago, IL 60618, USA                      769
  5000 South Union Avenue, Chicago, IL 60609, USA                          769
                                                                          ...
  3300 West Randolph Street, Chicago, IL 60612, USA                        760
  2900 West 85th Street, Chicago, IL 60652, USA                            760
  West 37th Place, Chicago, IL, USA                                        760
  1700 North Ashland Avenue, Chicago, IL 60622, USA                        760
  South Avenue L, Chicago, IL 60617, USA                                   760
  2200 West 113th Street, Chicago, IL 60643, USA                           760
  5100 West 72nd Street, Chicago, IL 60638, USA                            760
  4700 South Cornell Avenue, Chicago, IL 60615, USA                        760
  3400 North Long Avenue, Chicago, IL 60641, USA                           760
  East 138th Street, Riverdale, IL 60827, USA                              760
  6400 South Stony Island Avenue, Chicago, IL 60637, USA                   760
  5200 South Nordica Avenue, Chicago, IL 60638, USA                        760
  1200 West Greenleaf Avenue, Chicago, IL 60626, USA                       760
  East 91st Street, Chicago, IL, USA                                       760
  2000 East 111th Street, Chicago, IL 60628, USA                           760
  4000 North Tripp Avenue, Chicago, IL 60641, USA                          760
  2100 South Hamlin Avenue, Chicago, IL 60623, USA                         760
  2600 East 136th Street, Chicago, IL 60633, USA                           760
  1500 West Granville Avenue, Chicago, IL 60660, USA                       760
  South Oglesby Avenue, Chicago, IL, USA                                   760
  1200 West 120th Street, Chicago, IL 60643, USA                           760
  North Streeter Drive, Chicago, IL 60611, USA                             760
  9800 South Avenue G, Chicago, IL 60617, USA                              760
  1800 West Leland Avenue, Chicago, IL 60640, USA                          760
  4000 North Kedvale Avenue, Chicago, IL 60641, USA                        760
  1100 South Loomis Street, Chicago, IL 60607, USA                         760
  South Wallace Street, Chicago, IL, USA                                   760
  3400 West 77th Street, Chicago, IL 60652, USA                            760
  1100 South State Street, Chicago, IL 60605, USA                          760
  6500 South Racine Avenue, Chicago, IL 60636, USA                         760
  Name: Address, dtype: int64, 'AddressAccuracy': 8    61973
  9    39795
  5    13761
  3      764
  Name: AddressAccuracy, dtype: int64, 'AddressNumberAndStreet': 1000  W OHARE AIRPORT, Chicago, IL       1468
  4100  N OAK PARK AVE, Chicago, IL         857
  7000  N MOSELL AVE, Chicago, IL           822
  3600  N PITTSBURGH AVE, Chicago, IL       814
  5800  N PULASKI RD, Chicago, IL           803
  7000   W ARMITAGE AVENUE, Chicago, IL     797
  2200  N CANNON DR, Chicago, IL            792
  1000  W OHARE, Chicago, IL                784
  5800  N WESTERN AVE, Chicago, IL          783
  5800  N RIDGE AVE, Chicago, IL            781
  6100  N LEMONT AVE, Chicago, IL           781
  4600  N MILWAUKEE AVE, Chicago, IL        780
  1200  S DOTY AVE, Chicago, IL             776
  4500  N CAMPBELL AVE, Chicago, IL         776
  1000  E 67TH ST, Chicago, IL              776
  7200  N OKETO AVE, Chicago, IL            775
  5100  N MONT CLARE AVE, Chicago, IL       774
  2400  E 105TH ST, Chicago, IL             774
  4200  W 127TH PL, Chicago, IL             774
  3700  S PULASKI RD, Chicago, IL           774
  3700  E 118TH ST, Chicago, IL             773
  3500  W 116TH ST, Chicago, IL             773
  1000  S COTTAGE GROVE, Chicago, IL        772
  5200  S KOLMAR, Chicago, IL               772
  1000  N CENTRAL PARK DR, Chicago, IL      771
  8900  S CARPENTER ST, Chicago, IL         770
  5000  S UNION AVE, Chicago, IL            769
  6100  W FULLERTON AVE, Chicago, IL        769
  4000  E 130TH ST, Chicago, IL             769
  2800  N FRANCISCO AVE, Chicago, IL        769
                                           ...
  8900  S MUSKEGON AVE, Chicago, IL         760
  8000  S KEDZIE AVE, Chicago, IL           760
  1800  W LELAND AVE, Chicago, IL           760
  4000  N TRIPP AVE, Chicago, IL            760
  2100  S HAMLIN AVE, Chicago, IL           760
  7100  S SOUTH SHORE DR, Chicago, IL       760
  4600  N MELVINA AVE, Chicago, IL          760
  4900  W BALMORAL AVE, Chicago, IL         760
  4700  S CORNELL AVE, Chicago, IL          760
  6100  S MELVINA AVE, Chicago, IL          760
  6800  W BELDEN AVE, Chicago, IL           760
  1000  W 95TH ST, Chicago, IL              760
  5300  N STREETER DR, Chicago, IL          760
  2200  W PERSHING RD, Chicago, IL          760
  6000  W MONTROSE DR, Chicago, IL          760
  1200  W GREENLEAF AVE, Chicago, IL        760
  1500  W GRANVILLE AVE, Chicago, IL        760
  6400  S STONY ISLAND AVE, Chicago, IL     760
  1700  N ASHLAND AVE, Chicago, IL          760
  6600  S KILPATRICK AVE, Chicago, IL       760
  6000  W ROSCOE ST, Chicago, IL            760
  5300  W AGATITE AVE, Chicago, IL          760
  2000  E 111TH ST, Chicago, IL             760
  1100  S WALLACE ST, Chicago, IL           760
  2900  W 85TH ST, Chicago, IL              760
  2200  W 89TH ST, Chicago, IL              760
  8100  W 37TH PL., Chicago, IL             760
  6300  W 64TH ST, Chicago, IL              760
  2100  N STAVE ST, Chicago, IL             760
  1100  S PEORIA ST, Chicago, IL            760
  Name: AddressNumberAndStreet, dtype: int64, 'Block': 10    8384
  11    7614
  22    4596
  40    3809
  37    3076
  12    3062
  42    3055
  13    3050
  17    3043
  65    3042
  21    3040
  58    2367
  61    2310
  51    2301
  52    2297
  33    2287
  25    2286
  15    2282
  60    2280
  70    1619
  46    1540
  35    1535
  50    1532
  39    1532
  89    1530
  14    1530
  91    1528
  82    1526
  71    1525
  79    1523
        ...
  49    1520
  30    1520
  96    1520
  34    1520
  18    1520
  81    1520
  41     857
  36     814
  45     776
  72     775
  24     774
  28     769
  77     767
  43     764
  55     763
  67     763
  48     762
  75     761
  80     760
  26     760
  66     760
  68     760
  90     760
  73     760
  93     760
  27     760
  47     760
  20     760
  98     760
  63     760
  Name: Block, dtype: int64, 'Date': 2012-07-09    1293
  2012-08-03    1282
  2012-07-27    1282
  2012-07-19    1260
  2010-07-13    1257
  2012-07-13    1256
  2014-08-14    1254
  2014-08-21    1253
  2008-09-09    1248
  2008-09-02    1247
  2014-08-07    1247
  2008-08-19    1247
  2012-07-20    1245
  2014-07-31    1245
  2010-07-19    1241
  2014-06-19    1236
  2014-08-28    1234
  2008-07-24    1234
  2008-08-13    1233
  2014-07-10    1233
  2008-08-26    1232
  2012-08-10    1231
  2012-06-29    1231
  2012-08-17    1229
  2010-07-26    1229
  2014-07-03    1229
  2014-09-05    1229
  2010-06-28    1227
  2010-08-20    1225
  2010-07-30    1225
                ...
  2012-09-20    1214
  2010-09-24    1214
  2008-08-12    1214
  2012-06-15    1214
  2008-08-04    1213
  2012-06-08    1213
  2012-08-09    1213
  2008-09-03    1213
  2010-06-02    1212
  2008-07-01    1211
  2010-06-11    1211
  2010-07-29    1211
  2008-09-19    1211
  2010-09-10    1210
  2008-07-28    1210
  2010-08-26    1210
  2010-06-18    1209
  2010-08-19    1209
  2012-08-30    1209
  2010-08-05    1209
  2008-07-11    1209
  2008-07-04    1209
  2010-09-23    1208
  2014-10-02    1208
  2008-06-17    1208
  2008-06-11    1208
  2010-09-16    1208
  2012-08-23    1208
  2010-07-01    1208
  2008-07-21    1208
  Name: Date, dtype: int64, 'Id': 2047      1
  7465      1
  70920     1
  72969     1
  66826     1
  68875     1
  79116     1
  81165     1
  75022     1
  77071     1
  115986    1
  103704    1
  105753    1
  99610     1
  101659    1
  111900    1
  113949    1
  107806    1
  109855    1
  21792     1
  23841     1
  17698     1
  19747     1
  29988     1
  32037     1
  25894     1
  27943     1
  93447     1
  91398     1
  97541     1
           ..
  111331    1
  62155     1
  58057     1
  115309    1
  94843     1
  76400     1
  74353     1
  80498     1
  78451     1
  68212     1
  66165     1
  72310     1
  70263     1
  92792     1
  90745     1
  96890     1
  84604     1
  60104     1
  82557     1
  88702     1
  86655     1
  43712     1
  41665     1
  47810     1
  45763     1
  35524     1
  33477     1
  39622     1
  37575     1
  2049      1
  Name: Id, dtype: int64, 'Latitude': 41.974689    1468
  41.954690     857
  42.008314     822
  41.944869     814
  41.984809     803
  41.916265     797
  41.921965     792
  41.957799     784
  41.986921     783
  41.991429     781
  41.987280     781
  41.964242     780
  41.773215     776
  41.673408     776
  41.963976     776
  42.011601     775
  41.973845     774
  41.662014     774
  41.825610     774
  41.704572     774
  41.682587     773
  41.680946     773
  41.798697     772
  41.750498     772
  41.899230     771
  41.732984     770
  41.659112     769
  41.932094     769
  41.803423     769
  41.923738     769
               ...
  41.862292     760
  41.721474     760
  41.729669     760
  41.836644     760
  41.918705     760
  41.747850     760
  41.775051     760
  41.919343     760
  41.949830     760
  41.868533     760
  41.942285     760
  42.010412     760
  41.778748     760
  41.912563     760
  41.731922     760
  41.719140     760
  41.869107     760
  41.990284     760
  41.799282     760
  41.966987     760
  41.846283     760
  41.907645     760
  41.717753     760
  41.960616     760
  41.961743     760
  41.797616     760
  41.781416     760
  41.644612     760
  41.883284     760
  41.852652     760
  Name: Latitude, dtype: int64, 'Longitude': -87.890615    1468
  -87.800991     857
  -87.777921     822
  -87.832763     814
  -87.728492     803
  -87.800515     797
  -87.632085     792
  -87.930995     784
  -87.689778     783
  -87.747113     781
  -87.666066     781
  -87.757639     780
  -87.691810     776
  -87.599862     776
  -87.600880     776
  -87.811506     775
  -87.726549     774
  -87.724608     774
  -87.805059     774
  -87.565666     774
  -87.707973     773
  -87.535198     773
  -87.605294     772
  -87.736812     772
  -87.716788     771
  -87.649642     770
  -87.700117     769
  -87.538693     769
  -87.785288     769
  -87.642984     769
                ...
  -87.781978     760
  -87.730890     760
  -87.719887     760
  -87.661638     760
  -87.668055     760
  -87.531657     760
  -87.582699     760
  -87.678378     760
  -87.812827     760
  -87.531635     760
  -87.776385     760
  -87.627561     760
  -87.698457     760
  -87.604498     760
  -87.675088     760
  -87.662140     760
  -87.795585     760
  -87.655356     760
  -87.745602     760
  -87.648064     760
  -87.776532     760
  -87.633590     760
  -87.797894     760
  -87.795180     760
  -87.761726     760
  -87.614258     760
  -87.695443     760
  -87.742302     760
  -87.776792     760
  -87.688267     760
  Name: Longitude, dtype: int64, 'Species': CULEX PIPIENS/RESTUANS    15359
  CULEX RESTUANS            14670
  CULEX PIPIENS             14521
  CULEX SALINARIUS          14355
  CULEX TERRITANS           14351
  CULEX TARSALIS            14347
  CULEX ERRATICUS           14345
  UNSPECIFIED CULEX         14345
  Name: Species, dtype: int64, 'Street':  N OAK PARK AVE                   1617
   N PULASKI RD                     1564
   N CANNON DR                      1552
   S ASHLAND AVE                    1531
   S STONY ISLAND AVE               1528
   N KEDVALE AVE                    1527
   W 51ST ST                        1524
   S KEDZIE AVE                     1523
   S DR MARTIN LUTHER KING JR DR    1523
   W 95TH ST                        1521
   S HOYNE AVE                      1520
   N LONG AVE                       1520
   W OHARE AIRPORT                  1468
   N MOSELL AVE                      822
   N PITTSBURGH AVE                  814
    W ARMITAGE AVENUE                797
   W OHARE                           784
   N WESTERN AVE                     783
   N LEMONT AVE                      781
   N RIDGE AVE                       781
   N MILWAUKEE AVE                   780
   N CAMPBELL AVE                    776
   S DOTY AVE                        776
   E 67TH ST                         776
   N OKETO AVE                       775
   E 105TH ST                        774
   S PULASKI RD                      774
   W 127TH PL                        774
   N MONT CLARE AVE                  774
   E 118TH ST                        773
                                    ...
   W GRANVILLE AVE                   760
   N CALIFORNIA AVE                  760
   W ROSCOE ST                       760
   E 138TH ST                        760
   W 89TH ST                         760
   W FARWELL AVE                     760
   W HIGGINS AVE                     760
   S SOUTH SHORE DR                  760
   N LAWLER AVE                      760
   W GREENLEAF AVE                   760
   W DAKIN ST                        760
   S NORDICA                         760
   W BALMORAL AVE                    760
   S OGLESBY AVE                     760
   S STATE ST                        760
   W PERSHING RD                     760
   W BELDEN AVE                      760
   N STREETER DR                     760
   S WESTERN AVE                     760
   N MANDELL AVE                     760
   N AVONDALE AVE                    760
   W 72ND ST                         760
   S ARTESIAN AVE                    760
   S CICERO AVE                      760
   N AUSTIN AVE                      760
   W 37TH PL.                        760
   W SUNNYSIDE AVE                   760
   W 31ST ST                         760
   W GARFIELD BLVD                   760
   S HAMLIN AVE                      760
  Name: Street, dtype: int64, 'Trap': T009     1528
  T035     1520
  T900     1468
  T002      857
  T008      822
  T011      814
  T027      803
  T151      797
  T054      792
  T903      784
  T028      783
  T231      781
  T012      781
  T003      780
  T220      776
  T073      776
  T115      776
  T016      775
  T063      774
  T223      774
  T135      774
  T128      774
  T212      773
  T158      773
  T102      772
  T114      772
  T030      771
  T159      770
  T013      769
  T147      769
           ...
  T149      760
  T025      760
  T218A     760
  T088      760
  T086      760
  T034      760
  T037      760
  T036      760
  T007      760
  T006      760
  T005      760
  T004      760
  T219      760
  T096      760
  T079      760
  T078      760
  T075      760
  T097      760
  T077      760
  T162      760
  T071      760
  T070      760
  T090C     760
  T072      760
  T091      760
  T092      760
  T001      760
  T142      760
  T143      760
  T081      760
  Name: Trap, dtype: int64},
 'table': {'CAT': 6,
  'CONST': 0,
  'CORR': 0,
  'DATE': 0,
  'NUM': 5,
  'RECODED': 0,
  'REJECTED': 0,
  'UNIQUE': 0,
  'memsize': '9.8 MiB',
  'n': 116293,
  'n_duplicates': 0,
  'nvar': 11,
  'recordsize': '88.0 B',
  'total_missing': 0.0},
 'variables':                          count distinct_count is_unique memorysize  \
 Address                 116293            151     False     930416
 AddressAccuracy         116293              4     False     930416
 AddressNumberAndStreet  116293            151     False     930416
 Block                   116293             65     False     930416
 Date                    116293             95     False     930416
 Id                      116293         116293      True     930416
 Latitude                116293            151     False     930416
 Longitude               116293            151     False     930416
 Species                 116293              8     False     930416
 Street                  116293            139     False     930416
 Trap                    116293            149     False     930416

                                                                      mode  \
 Address                 ORD Terminal 5, O'Hare International Airport, ...
 AddressAccuracy                                                         8
 AddressNumberAndStreet                 1000  W OHARE AIRPORT, Chicago, IL
 Block                                                                  10
 Date                                                           2012-07-09
 Id                                                                      1
 Latitude                                                          41.9747
 Longitude                                                        -87.8906
 Species                                            CULEX PIPIENS/RESTUANS
 Street                                                     N OAK PARK AVE
 Trap                                                                 T009

                        n_infinite n_missing p_infinite p_missing     p_unique  \
 Address                         0         0          0         0   0.00129844
 AddressAccuracy                 0         0          0         0  3.43959e-05
 AddressNumberAndStreet          0         0          0         0   0.00129844
 Block                           0         0          0         0  0.000558933
 Date                            0         0          0         0  0.000816902
 Id                              0         0          0         0            1

In [42]:
# EDA function 
def eda(dataframe):
    print "missing values \n", dataframe.isnull().sum() #count how many null values are in each series
    print "dataframe types \n", dataframe.dtypes # check data types of each colum
    print "dataframe shape \n", dataframe.shape # gives us the number of rows and columns
    print "dataframe describe \n", dataframe.describe() # descriptive statistics
    for item in dataframe:
        print item
        print dataframe[item].nunique() # print number of unique observations

In [43]:
eda(test)

missing values
Date                      0
Address                   0
Species                   0
Block                     0
Street                    0
Trap                      0
AddressNumberAndStreet    0
Latitude                  0
Longitude                 0
AddressAccuracy           0
dtype: int64
dataframe types
Date                       object
Address                    object
Species                    object
Block                       int64
Street                     object
Trap                       object
AddressNumberAndStreet     object
Latitude                  float64
Longitude                 float64
AddressAccuracy             int64
dtype: object
dataframe shape
(116293, 10)
dataframe describe
               Block       Latitude      Longitude  AddressAccuracy
count  116293.000000  116293.000000  116293.000000    116293.000000
mean       41.131100      41.849389     -87.693658         7.954357
std        24.864726       0.106593       0.080699         1.252733
min        10.000000      41.644612     -87.930995         3.000000
25%        18.000000      41.753411     -87.750938         8.000000
50%        39.000000      41.862292     -87.694991         8.000000
75%        61.000000      41.951866     -87.648860         9.000000
max        98.000000      42.017430     -87.531635         9.000000
Date
95
Address
151
Species
8
Block
65
Street
139
Trap
149
AddressNumberAndStreet
151
Latitude
151
Longitude
151
AddressAccuracy
4

In [44]:
test.columns

Index([u'Date', u'Address', u'Species', u'Block', u'Street', u'Trap',
       u'AddressNumberAndStreet', u'Latitude', u'Longitude',
       u'AddressAccuracy'],
      dtype='object')

In [45]:
test.AddressAccuracy.unique()

array([9, 8, 5, 3])

In [46]:
test.Trap.unique()

array(['T002', 'T007', 'T015', 'T045', 'T046', 'T048', 'T049', 'T050',
       'T054', 'T086', 'T091', 'T094', 'T096', 'T129', 'T143', 'T148',
       'T153', 'T159', 'T009', 'T011', 'T016', 'T019', 'T025', 'T028',
       'T031', 'T033', 'T089', 'T090', 'T092', 'T135', 'T141', 'T142',
       'T145', 'T146', 'T147', 'T149', 'T150', 'T151', 'T152', 'T154',
       'T158', 'T162', 'T218', 'T220', 'T001', 'T003', 'T006', 'T008',
       'T012', 'T034', 'T037', 'T040', 'T043', 'T047', 'T051', 'T085',
       'T088', 'T161', 'T219', 'T013', 'T014', 'T018', 'T030', 'T084',
       'T144', 'T160', 'T005', 'T017', 'T044', 'T095', 'T004', 'T035',
       'T036', 'T039', 'T060', 'T061', 'T062', 'T065', 'T066', 'T067',
       'T069', 'T070', 'T071', 'T073', 'T074', 'T075', 'T076', 'T077',
       'T079', 'T080', 'T081', 'T082', 'T083', 'T114', 'T155', 'T063',
       'T115', 'T138', 'T200', 'T206', 'T209', 'T212', 'T215', 'T107',
       'T128', 'T072', 'T078', 'T097', 'T099', 'T100', 'T102', 'T103',
       'T027', 'T156', 'T157', 'T221', 'T900', 'T903', 'T090A', 'T090B',
       'T090C', 'T200A', 'T128A', 'T200B', 'T218A', 'T218C', 'T218B',
       'T222', 'T223', 'T225', 'T227', 'T224', 'T226', 'T229', 'T230',
       'T228', 'T231', 'T232', 'T002A', 'T002B', 'T233', 'T234', 'T235',
       'T236', 'T237', 'T238', 'T065A', 'T094B', 'T054C'], dtype=object)

In [47]:
test.Species.value_counts()

CULEX PIPIENS/RESTUANS    15359
CULEX RESTUANS            14670
CULEX PIPIENS             14521
CULEX SALINARIUS          14355
CULEX TERRITANS           14351
CULEX TARSALIS            14347
CULEX ERRATICUS           14345
UNSPECIFIED CULEX         14345
Name: Species, dtype: int64

In [48]:
test["New Date"] = pd.to_datetime(test.Date)

In [49]:
test["Year"] = test['New Date'].dt.year

In [50]:
test['Week'] = test['New Date'].dt.week

In [51]:
test['Month'] = test['New Date'].dt.month

In [54]:
 for item in test:
        print item
        print test[item].value_counts()

Date
2012-07-09    1293
2012-08-03    1282
2012-07-27    1282
2012-07-19    1260
2010-07-13    1257
2012-07-13    1256
2014-08-14    1254
2014-08-21    1253
2008-09-09    1248
2008-09-02    1247
2014-08-07    1247
2008-08-19    1247
2012-07-20    1245
2014-07-31    1245
2010-07-19    1241
2014-06-19    1236
2014-08-28    1234
2008-07-24    1234
2008-08-13    1233
2014-07-10    1233
2008-08-26    1232
2012-08-10    1231
2012-06-29    1231
2012-08-17    1229
2010-07-26    1229
2014-07-03    1229
2014-09-05    1229
2010-06-28    1227
2010-08-20    1225
2010-07-30    1225
              ...
2012-09-20    1214
2010-09-24    1214
2008-08-12    1214
2012-06-15    1214
2008-08-04    1213
2012-06-08    1213
2012-08-09    1213
2008-09-03    1213
2010-06-02    1212
2008-07-01    1211
2010-06-11    1211
2010-07-29    1211
2008-09-19    1211
2010-09-10    1210
2008-07-28    1210
2010-08-26    1210
2010-06-18    1209
2010-08-19    1209
2012-08-30    1209
2010-08-05    1209
2008-07-11    1209
2008-07-04    1209
2010-09-23    1208
2014-10-02    1208
2008-06-17    1208
2008-06-11    1208
2010-09-16    1208
2012-08-23    1208
2010-07-01    1208
2008-07-21    1208
Name: Date, dtype: int64
Address
ORD Terminal 5, O'Hare International Airport, Chicago, IL 60666, USA    1468
4100 North Oak Park Avenue, Chicago, IL 60634, USA                       857
7000 North Moselle Avenue, Chicago, IL 60646, USA                        822
3600 North Pittsburgh Avenue, Chicago, IL 60634, USA                     814
5800 North Pulaski Road, Chicago, IL 60646, USA                          803
7000 West Armitage Avenue, Chicago, IL 60707, USA                        797
2200 North Cannon Drive, Chicago, IL 60614, USA                          792
Ohare Court, Bensenville, IL 60106, USA                                  784
5800 North Western Avenue, Chicago, IL 60659, USA                        783
6100 North Lemont Avenue, Chicago, IL 60646, USA                         781
5800 North Ridge Avenue, Chicago, IL 60660, USA                          781
4600 Milwaukee Avenue, Chicago, IL 60630, USA                            780
1000 East 67th Street, Chicago, IL 60637, USA                            776
South Doty Avenue, Chicago, IL, USA                                      776
4500 North Campbell Avenue, Chicago, IL 60625, USA                       776
7200 North Oketo Avenue, Chicago, IL 60631, USA                          775
5100 North Mont Clare Avenue, Chicago, IL 60656, USA                     774
4200 West 127th Street, Alsip, IL 60803, USA                             774
2400 East 105th Street, Chicago, IL 60617, USA                           774
3700 South Pulaski Road, Chicago, IL 60623, USA                          774
3700 118th Street, Chicago, IL 60617, USA                                773
3500 West 116th Street, Chicago, IL 60655, USA                           773
5200 South Kolmar Avenue, Chicago, IL 60632, USA                         772
South Cottage Grove Avenue, Chicago, IL, USA                             772
1000 North Central Park Avenue, Chicago, IL 60651, USA                   771
8900 South Carpenter Street, Chicago, IL 60620, USA                      770
4000 East 130th Street, Chicago, IL 60633, USA                           769
6100 West Fullerton Avenue, Chicago, IL 60639, USA                       769
2800 North Francisco Avenue, Chicago, IL 60618, USA                      769
5000 South Union Avenue, Chicago, IL 60609, USA                          769
                                                                        ...
3300 West Randolph Street, Chicago, IL 60612, USA                        760
2900 West 85th Street, Chicago, IL 60652, USA                            760
West 37th Place, Chicago, IL, USA                                        760
1700 North Ashland Avenue, Chicago, IL 60622, USA                        760
South Avenue L, Chicago, IL 60617, USA                                   760
2200 West 113th Street, Chicago, IL 60643, USA                           760
5100 West 72nd Street, Chicago, IL 60638, USA                            760
4700 South Cornell Avenue, Chicago, IL 60615, USA                        760
3400 North Long Avenue, Chicago, IL 60641, USA                           760
East 138th Street, Riverdale, IL 60827, USA                              760
6400 South Stony Island Avenue, Chicago, IL 60637, USA                   760
5200 South Nordica Avenue, Chicago, IL 60638, USA                        760
1200 West Greenleaf Avenue, Chicago, IL 60626, USA                       760
East 91st Street, Chicago, IL, USA                                       760
2000 East 111th Street, Chicago, IL 60628, USA                           760
4000 North Tripp Avenue, Chicago, IL 60641, USA                          760
2100 South Hamlin Avenue, Chicago, IL 60623, USA                         760
2600 East 136th Street, Chicago, IL 60633, USA                           760
1500 West Granville Avenue, Chicago, IL 60660, USA                       760
South Oglesby Avenue, Chicago, IL, USA                                   760
1200 West 120th Street, Chicago, IL 60643, USA                           760
North Streeter Drive, Chicago, IL 60611, USA                             760
9800 South Avenue G, Chicago, IL 60617, USA                              760
1800 West Leland Avenue, Chicago, IL 60640, USA                          760
4000 North Kedvale Avenue, Chicago, IL 60641, USA                        760
1100 South Loomis Street, Chicago, IL 60607, USA                         760
South Wallace Street, Chicago, IL, USA                                   760
3400 West 77th Street, Chicago, IL 60652, USA                            760
1100 South State Street, Chicago, IL 60605, USA                          760
6500 South Racine Avenue, Chicago, IL 60636, USA                         760
Name: Address, dtype: int64
Species
CULEX PIPIENS/RESTUANS    15359
CULEX RESTUANS            14670
CULEX PIPIENS             14521
CULEX SALINARIUS          14355
CULEX TERRITANS           14351
CULEX TARSALIS            14347
CULEX ERRATICUS           14345
UNSPECIFIED CULEX         14345
Name: Species, dtype: int64
Block
10    8384
11    7614
22    4596
40    3809
37    3076
12    3062
42    3055
13    3050
17    3043
65    3042
21    3040
58    2367
61    2310
51    2301
52    2297
33    2287
25    2286
15    2282
60    2280
70    1619
46    1540
35    1535
50    1532
39    1532
89    1530
14    1530
91    1528
82    1526
71    1525
79    1523
      ...
49    1520
30    1520
96    1520
34    1520
18    1520
81    1520
41     857
36     814
45     776
72     775
24     774
28     769
77     767
43     764
55     763
67     763
48     762
75     761
80     760
26     760
66     760
68     760
90     760
73     760
93     760
27     760
47     760
20     760
98     760
63     760
Name: Block, dtype: int64
Street
 N OAK PARK AVE                   1617
 N PULASKI RD                     1564
 N CANNON DR                      1552
 S ASHLAND AVE                    1531
 S STONY ISLAND AVE               1528
 N KEDVALE AVE                    1527
 W 51ST ST                        1524
 S KEDZIE AVE                     1523
 S DR MARTIN LUTHER KING JR DR    1523
 W 95TH ST                        1521
 S HOYNE AVE                      1520
 N LONG AVE                       1520
 W OHARE AIRPORT                  1468
 N MOSELL AVE                      822
 N PITTSBURGH AVE                  814
  W ARMITAGE AVENUE                797
 W OHARE                           784
 N WESTERN AVE                     783
 N LEMONT AVE                      781
 N RIDGE AVE                       781
 N MILWAUKEE AVE                   780
 N CAMPBELL AVE                    776
 S DOTY AVE                        776
 E 67TH ST                         776
 N OKETO AVE                       775
 E 105TH ST                        774
 S PULASKI RD                      774
 W 127TH PL                        774
 N MONT CLARE AVE                  774
 E 118TH ST                        773
                                  ...
 W GRANVILLE AVE                   760
 N CALIFORNIA AVE                  760
 W ROSCOE ST                       760
 E 138TH ST                        760
 W 89TH ST                         760
 W FARWELL AVE                     760
 W HIGGINS AVE                     760
 S SOUTH SHORE DR                  760
 N LAWLER AVE                      760
 W GREENLEAF AVE                   760
 W DAKIN ST                        760
 S NORDICA                         760
 W BALMORAL AVE                    760
 S OGLESBY AVE                     760
 S STATE ST                        760
 W PERSHING RD                     760
 W BELDEN AVE                      760
 N STREETER DR                     760
 S WESTERN AVE                     760
 N MANDELL AVE                     760
 N AVONDALE AVE                    760
 W 72ND ST                         760
 S ARTESIAN AVE                    760
 S CICERO AVE                      760
 N AUSTIN AVE                      760
 W 37TH PL.                        760
 W SUNNYSIDE AVE                   760
 W 31ST ST                         760
 W GARFIELD BLVD                   760
 S HAMLIN AVE                      760
Name: Street, dtype: int64
Trap
T009     1528
T035     1520
T900     1468
T002      857
T008      822
T011      814
T027      803
T151      797
T054      792
T903      784
T028      783
T231      781
T012      781
T003      780
T220      776
T073      776
T115      776
T016      775
T063      774
T223      774
T135      774
T128      774
T212      773
T158      773
T102      772
T114      772
T030      771
T159      770
T013      769
T147      769
         ...
T149      760
T025      760
T218A     760
T088      760
T086      760
T034      760
T037      760
T036      760
T007      760
T006      760
T005      760
T004      760
T219      760
T096      760
T079      760
T078      760
T075      760
T097      760
T077      760
T162      760
T071      760
T070      760
T090C     760
T072      760
T091      760
T092      760
T001      760
T142      760
T143      760
T081      760
Name: Trap, dtype: int64
AddressNumberAndStreet
1000  W OHARE AIRPORT, Chicago, IL       1468
4100  N OAK PARK AVE, Chicago, IL         857
7000  N MOSELL AVE, Chicago, IL           822
3600  N PITTSBURGH AVE, Chicago, IL       814
5800  N PULASKI RD, Chicago, IL           803
7000   W ARMITAGE AVENUE, Chicago, IL     797
2200  N CANNON DR, Chicago, IL            792
1000  W OHARE, Chicago, IL                784
5800  N WESTERN AVE, Chicago, IL          783
5800  N RIDGE AVE, Chicago, IL            781
6100  N LEMONT AVE, Chicago, IL           781
4600  N MILWAUKEE AVE, Chicago, IL        780
1200  S DOTY AVE, Chicago, IL             776
4500  N CAMPBELL AVE, Chicago, IL         776
1000  E 67TH ST, Chicago, IL              776
7200  N OKETO AVE, Chicago, IL            775
5100  N MONT CLARE AVE, Chicago, IL       774
2400  E 105TH ST, Chicago, IL             774
4200  W 127TH PL, Chicago, IL             774
3700  S PULASKI RD, Chicago, IL           774
3700  E 118TH ST, Chicago, IL             773
3500  W 116TH ST, Chicago, IL             773
1000  S COTTAGE GROVE, Chicago, IL        772
5200  S KOLMAR, Chicago, IL               772
1000  N CENTRAL PARK DR, Chicago, IL      771
8900  S CARPENTER ST, Chicago, IL         770
5000  S UNION AVE, Chicago, IL            769
6100  W FULLERTON AVE, Chicago, IL        769
4000  E 130TH ST, Chicago, IL             769
2800  N FRANCISCO AVE, Chicago, IL        769
                                         ...
8900  S MUSKEGON AVE, Chicago, IL         760
8000  S KEDZIE AVE, Chicago, IL           760
1800  W LELAND AVE, Chicago, IL           760
4000  N TRIPP AVE, Chicago, IL            760
2100  S HAMLIN AVE, Chicago, IL           760
7100  S SOUTH SHORE DR, Chicago, IL       760
4600  N MELVINA AVE, Chicago, IL          760
4900  W BALMORAL AVE, Chicago, IL         760
4700  S CORNELL AVE, Chicago, IL          760
6100  S MELVINA AVE, Chicago, IL          760
6800  W BELDEN AVE, Chicago, IL           760
1000  W 95TH ST, Chicago, IL              760
5300  N STREETER DR, Chicago, IL          760
2200  W PERSHING RD, Chicago, IL          760
6000  W MONTROSE DR, Chicago, IL          760
1200  W GREENLEAF AVE, Chicago, IL        760
1500  W GRANVILLE AVE, Chicago, IL        760
6400  S STONY ISLAND AVE, Chicago, IL     760
1700  N ASHLAND AVE, Chicago, IL          760
6600  S KILPATRICK AVE, Chicago, IL       760
6000  W ROSCOE ST, Chicago, IL            760
5300  W AGATITE AVE, Chicago, IL          760
2000  E 111TH ST, Chicago, IL             760
1100  S WALLACE ST, Chicago, IL           760
2900  W 85TH ST, Chicago, IL              760
2200  W 89TH ST, Chicago, IL              760
8100  W 37TH PL., Chicago, IL             760
6300  W 64TH ST, Chicago, IL              760
2100  N STAVE ST, Chicago, IL             760
1100  S PEORIA ST, Chicago, IL            760
Name: AddressNumberAndStreet, dtype: int64
Latitude
41.974689    1468
41.954690     857
42.008314     822
41.944869     814
41.984809     803
41.916265     797
41.921965     792
41.957799     784
41.986921     783
41.991429     781
41.987280     781
41.964242     780
41.773215     776
41.673408     776
41.963976     776
42.011601     775
41.973845     774
41.662014     774
41.825610     774
41.704572     774
41.682587     773
41.680946     773
41.798697     772
41.750498     772
41.899230     771
41.732984     770
41.659112     769
41.932094     769
41.803423     769
41.923738     769
             ...
41.862292     760
41.721474     760
41.729669     760
41.836644     760
41.918705     760
41.747850     760
41.775051     760
41.919343     760
41.949830     760
41.868533     760
41.942285     760
42.010412     760
41.778748     760
41.912563     760
41.731922     760
41.719140     760
41.869107     760
41.990284     760
41.799282     760
41.966987     760
41.846283     760
41.907645     760
41.717753     760
41.960616     760
41.961743     760
41.797616     760
41.781416     760
41.644612     760
41.883284     760
41.852652     760
Name: Latitude, dtype: int64
Longitude
-87.890615    1468
-87.800991     857
-87.777921     822
-87.832763     814
-87.728492     803
-87.800515     797
-87.632085     792
-87.930995     784
-87.689778     783
-87.747113     781
-87.666066     781
-87.757639     780
-87.691810     776
-87.599862     776
-87.600880     776
-87.811506     775
-87.726549     774
-87.724608     774
-87.805059     774
-87.565666     774
-87.707973     773
-87.535198     773
-87.605294     772
-87.736812     772
-87.716788     771
-87.649642     770
-87.700117     769
-87.538693     769
-87.785288     769
-87.642984     769
              ...
-87.781978     760
-87.730890     760
-87.719887     760
-87.661638     760
-87.668055     760
-87.531657     760
-87.582699     760
-87.678378     760
-87.812827     760
-87.531635     760
-87.776385     760
-87.627561     760
-87.698457     760
-87.604498     760
-87.675088     760
-87.662140     760
-87.795585     760
-87.655356     760
-87.745602     760
-87.648064     760
-87.776532     760
-87.633590     760
-87.797894     760
-87.795180     760
-87.761726     760
-87.614258     760
-87.695443     760
-87.742302     760
-87.776792     760
-87.688267     760
Name: Longitude, dtype: int64
AddressAccuracy
8    61973
9    39795
5    13761
3      764
Name: AddressAccuracy, dtype: int64
New Date
2012-07-09    1293
2012-08-03    1282
2012-07-27    1282
2012-07-19    1260
2010-07-13    1257
2012-07-13    1256
2014-08-14    1254
2014-08-21    1253
2008-09-09    1248
2008-09-02    1247
2014-08-07    1247
2008-08-19    1247
2014-07-31    1245
2012-07-20    1245
2010-07-19    1241
2014-06-19    1236
2014-08-28    1234
2008-07-24    1234
2014-07-10    1233
2008-08-13    1233
2008-08-26    1232
2012-06-29    1231
2012-08-10    1231
2014-07-03    1229
2010-07-26    1229
2012-08-17    1229
2014-09-05    1229
2010-06-28    1227
2014-06-12    1225
2010-08-20    1225
              ...
2010-09-24    1214
2008-08-12    1214
2012-09-20    1214
2012-06-15    1214
2012-08-09    1213
2008-08-04    1213
2012-06-08    1213
2008-09-03    1213
2010-06-02    1212
2010-06-11    1211
2008-07-01    1211
2008-09-19    1211
2010-07-29    1211
2010-08-26    1210
2010-09-10    1210
2008-07-28    1210
2008-07-04    1209
2012-08-30    1209
2010-06-18    1209
2010-08-19    1209
2010-08-05    1209
2008-07-11    1209
2012-08-23    1208
2014-10-02    1208
2010-07-01    1208
2008-06-11    1208
2008-07-21    1208
2008-06-17    1208
2010-09-16    1208
2010-09-23    1208
Name: New Date, dtype: int64
Year
2010    36557
2008    30498
2012    27115
2014    22123
Name: Year, dtype: int64
Week
30    9819
28    8686
33    8580
37    8563
29    7405
31    7392
34    7360
32    7346
35    7331
26    7321
38    7284
36    4899
25    4876
24    4856
27    3649
39    3648
23    3642
40    2424
22    1212
Name: Week, dtype: int64
Month
7     35665
8     33115
9     25612
6     19478
10     2423
Name: Month, dtype: int64